### ISSUE TITLE
License

### ISSUE THREAD

**Issue by lodi** [aiberia/persistent-evdev#1]
Thank you so much for this software.  I was going nuts constantly losing mouse/keyboard support in my qemu vm's due to flaky usb ports on my motherboard.

I packaged your program for [NixOS](https://github.com/NixOS/nixpkgs/pull/163226) so that other people can hopefully avoid the same headache.  I was wondering if you would consider relicensing your code under an open source license like [MIT](https://opensource.org/licenses/MIT)?  That would enable it to be used by all NixOS users, not just those that opt-in to proprietary packages.  Thanks in advance for you consideration.

**Comment by aiberia** [comment]
Added a MIT license

**Comment by lodi** [comment]
Perfect, thank you very much!
